[package]
name = "roactshopsystem/roact-shop-system"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Профессиональная система магазина для Roblox с использованием Roact"

[dependencies]
roact = "roblox/roact@^1.4.4"

[dev-dependencies]
