name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Luau
      uses: Kampfkarren/setup-luau@v1
      
    - name: Install Selene
      uses: NightrainsRbx/setup-selene@v1
      
    - name: Run Selene
      run: selene src/

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup StyLua
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check src/

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint, format]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rojo
      uses: rojo-rbx/setup-rojo@v1
      
    - name: Setup Wally
      uses: UpliftGames/setup-wally@v1
      
    - name: Install dependencies
      run: wally install
      
    - name: Build project
      run: rojo build -o RoactShopSystem.rbxlx
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: RoactShopSystem-${{ github.sha }}
        path: RoactShopSystem.rbxlx

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rojo
      uses: rojo-rbx/setup-rojo@v1
      
    - name: Setup Wally
      uses: UpliftGames/setup-wally@v1
      
    - name: Install dependencies
      run: wally install
      
    # TODO: Add actual test runner when available
    - name: Validate project structure
      run: |
        echo "Validating project structure..."
        test -f src/shared/Types.luau
        test -f src/services/CurrencyService.luau
        test -f src/services/ShopService.luau
        test -f src/App/AppController.luau
        echo "✅ Project structure validated"

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      run: |
        echo "🔒 Running security checks..."
        # Check for potential security issues in Luau files
        grep -r "require.*http" src/ || echo "No HTTP requires found"
        grep -r "loadstring" src/ || echo "No loadstring usage found"
        grep -r "_G\." src/ || echo "No global access found"
        echo "✅ Security scan completed"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, test, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Rojo
      uses: rojo-rbx/setup-rojo@v1
      
    - name: Setup Wally
      uses: UpliftGames/setup-wally@v1
      
    - name: Install dependencies
      run: wally install
      
    - name: Build release
      run: rojo build -o RoactShopSystem-release.rbxlx
      
    - name: Generate release notes
      run: |
        echo "# Release Notes" > release-notes.md
        echo "" >> release-notes.md
        echo "## Changes in this release:" >> release-notes.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)..HEAD >> release-notes.md
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body_path: release-notes.md
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: RoactShopSystem-release.rbxlx
        asset_name: RoactShopSystem.rbxlx
        asset_content_type: application/octet-stream
